In [19]:
import numpy as np
from numpy import pi

In [6]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [4]:
b = np.array([6,7,8])
print(b)
print(type(b))

[6 7 8]
<class 'numpy.ndarray'>


In [7]:
a = np.array([1,2,3,4])

In [8]:
b = np.array([(1.5, 2,3), (4,5,6)])
print(b)
print(b.dtype)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64


In [11]:
c = np.array([[1,2],[3,4]], dtype=complex)
print(c)
print(c.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [12]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
b = np.ones((2,3,4), dtype=np.int16)
print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [17]:
c = np.empty((2,3))
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [16]:
d = np.arange(10,30,7) #Que vaya de 10 a 30 en incrementos de 7
print(d)

[10 17 24]


In [18]:
e = np.linspace(0,2,9)
print(e)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [20]:
x = np.linspace(0,2*pi, 100)
print(x)
f = np.sin(x)
print(f)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [21]:
a = np.arange(6)
print('a:',a)

a: [0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4,3)
print('b: \n', b)

b: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
c = np.arange(24).reshape(2,3,4)
print('c with reshape(2,3,4): \n', c)
print("c's shape is: ", c.shape)

c with reshape(2,3,4): 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
c's shape is:  (2, 3, 4)


In [24]:
c = c.reshape(3,2,4)
print('c after reshape(3,2,4): \n', c)
print("c's shape is: ", c.shape)

c after reshape(3,2,4): 
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
c's shape is:  (3, 2, 4)


In [26]:
c = c.reshape(3,-1,4) #El -1 es un comodín
print('c after reshape(3,-1,4): \n', c)
print("c's shape is: ", c.shape)

c after reshape(3,-1,4): 
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
c's shape is:  (3, 2, 4)


In [27]:
c = c.reshape(3,-1) #El -1 es un comodín
print('c after reshape(3,-1): \n', c)
print("c's shape is: ", c.shape)

c after reshape(3,-1): 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
c's shape is:  (3, 8)


In [29]:
c = c.reshape(-1,3) #El -1 es un comodín
print('c after reshape(-1,3): \n', c)
print("c's shape is: ", c.shape)

c after reshape(-1,3): 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
c's shape is:  (8, 3)


In [30]:
c = c.reshape(-1) #El -1 es un comodín
print('c after reshape(-1): \n', c)
print("c's shape is: ", c.shape)

c after reshape(-1): 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
c's shape is:  (24,)


In [31]:
c = c.reshape(1, -1) #El -1 es un comodín
print('c after reshape(1,-1): \n', c)
print("c's shape is: ", c.shape)

c after reshape(1,-1): 
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
c's shape is:  (1, 24)


In [32]:
c = c.reshape(-1, 1) #El -1 es un comodín
print('c after reshape(-1,1): \n', c)
print("c's shape is: ", c.shape)

c after reshape(-1,1): 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
c's shape is:  (24, 1)


In [34]:
print("a few tests of copying by value or by references:")

print("first use numpy")
d = np.zeros((2,2))
e = d
d[0,0] = 2
print("d: ", d)
print("e: ", e)

a few tests of copying by value or by references:
first use numpy
d:  [[2. 0.]
 [0. 0.]]
e:  [[2. 0.]
 [0. 0.]]


In [36]:
a = np.array([1,2,3,4]).reshape(1,-1)
b = np.array([1,3,6]).reshape(-1,1)
c = (a==b)
d = (a * b)
e = (a + b)
f = (a > b)
print("a: ", a)
print("b: ", b)
print("c: ", c)
print("d: ", d)
print("e: ", e)
print("f: ", f)

a:  [[1 2 3 4]]
b:  [[1]
 [3]
 [6]]
c:  [[ True False False False]
 [False False  True False]
 [False False False False]]
d:  [[ 1  2  3  4]
 [ 3  6  9 12]
 [ 6 12 18 24]]
e:  [[ 2  3  4  5]
 [ 4  5  6  7]
 [ 7  8  9 10]]
f:  [[False  True  True  True]
 [False False False  True]
 [False False False False]]


Broadcasting
- Acomoda los arreglos para que sus dimensiones nos permitan operar
- Se debe poder progpagar una dimensión completa sobre otra

In [37]:
def simple_pred(df, theta):
    ftr = df.reshape(1,-1)
    pred = (ftr >= theta)
    print("feature: ", ftr)
    print("theta:", theta)
    print('predicction: ', pred)
    return pred

In [39]:
def simple_acc(ftr, outcome, theta):
    pred = simple_pred(ftr, theta)
    lbl = outcome.reshape(1,-1)
    cmp = (pred == lbl)
    acc = cmp.mean(axis = 1) #mean within each row (over columns). Es el promedio sobre todas las columnas del renglón

    print("outcome: ", lbl)
    print("comparison: ", cmp)
    print("accuaracy: ", acc)

    return acc

In [44]:
acc = simple_acc(np.array([150., 100., 110., 125.]).reshape(1,-1),np.array([True, True, False, False]).reshape(1,-1), np.array([120., 130.]).reshape(-1,1))

feature:  [[150. 100. 110. 125.]]
theta: [[120.]
 [130.]]
predicction:  [[ True False False  True]
 [ True False False False]]
outcome:  [[ True  True False False]]
comparison:  [[ True False  True False]
 [ True False  True  True]]
accuaracy:  [0.5  0.75]


In [45]:
acc = simple_acc(np.array([150., 100., 110., 125.]).reshape(1,-1),np.array([True, True, False, False]).reshape(1,-1), 120)

feature:  [[150. 100. 110. 125.]]
theta: 120
predicction:  [[ True False False  True]]
outcome:  [[ True  True False False]]
comparison:  [[ True False  True False]]
accuaracy:  [0.5]


In [46]:
acc = simple_acc(np.array([150., 100., 110., 125.]).reshape(1,-1), np.array([True, False, False, True]).reshape(1,-1), np.arange(100, 120).reshape(-1,1))

feature:  [[150. 100. 110. 125.]]
theta: [[100]
 [101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]
 [109]
 [110]
 [111]
 [112]
 [113]
 [114]
 [115]
 [116]
 [117]
 [118]
 [119]]
predicction:  [[ True  True  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]
 [ True False False  True]]
outcome:  [[ True False False  True]]
comparison:  [[ True False False  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True False  True]
 [ True  True False  Tr

In [51]:
a = np.array([(1,3,5), (4,7,10)])
b = np.array([3,.5,2,8]).reshape(-1,1)

mult = (a*b)
print(mult)

#NO SE PUEDE HACER EL BROADCASTING POR EL TAMAÑO DE LOS ARREGLOS

ValueError: operands could not be broadcast together with shapes (2,3) (4,1) 