In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
fp = 0
while (fp-1) > 0.0001:
    fp = fp + 0.1

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [5]:
a_mul_b = a * b
print(a_mul_b)

a_plus_b = a + b
print(a_plus_b)

a_minus_b = a - b
print(a_minus_b)

a_div_b = a / b
print(a_div_b)

a_pow_b = a ** b
print(a_pow_b)

[ 4 10 18]
[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[  1  32 729]
